### ISSUE TITLE
Duration and Duration Breakdown have the same icons

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/jaeger-ui#13]
![image.png](https://images.zenhubusercontent.com/63ec76164ec7e010c1af91fc/923597ae-bbe3-4e3f-873b-b4eefe16bc71)

See icons provided by inkode:
https://www.figma.com/file/ncRV3XUn1VltctY8LjlJFX/Digma-Design-System?type=design&node-id=6-153&t=43YRjmvH5NaxpZVY-0

**Comment by kshmidt-digma** [comment]
Closed with #11
